version: '3.9'

services:
  fintech-db:
    image: postgres:15
    container_name: fintech-db
    environment:
      POSTGRES_DB: fintech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
    ports:
      - "5432:5432"

  fintech-api:
    build:
      context: .
      dockerfile: src/FintechApp.Presentation/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=fintechdb2025.postgres.database.azure.com;Port=5432;Database=postgres;Username=postgres;Password=Fintech2025!Db12345;Ssl Mode=Require"
    ports:
      - "7118:80"
    depends_on:
      - fintech-db
